server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name _;

    root /var/www/tnaflex/webapp/public;
    index index.php;

    charset utf-8;
    client_max_body_size 10m;

    access_log /var/log/nginx/tnaflex-access.log;
    error_log /var/log/nginx/tnaflex-error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    location ~ ^/index\.php(/|$) {
        include fastcgi_params;

        fastcgi_param HTTPS $http_x_forwarded_proto;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_hide_header X-Powered-By;
        fastcgi_read_timeout 60s;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
