- name: Deploy new changes to the webapp and video-processing nodes
  hosts:
    - webapp-node
    - video-preprocessor-node
  any-errors-fatal: true
  tasks:
    - name: Pull latest changes from origin/master
      ansible.builtin.shell:
        cmd: git fetch origin master && git reset --hard origin/master && git clean -df
        chdir: /var/www/webapp

    - name: Update Backend dependencies
      ansible.builtin.command:
        cmd: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader
        chdir: /var/www/webapp

    - name: Clear cache
      ansible.builtin.command:
        cmd: php artisan optimize:clear
        chdir: /var/www/webapp

- name: Update database migration on the webapp node
  hosts:
    - webapp-node
  any-errors-fatal: true
  tasks:
    - name: Update Frontend dependencies
      ansible.builtin.shell:
        cmd: bun install --frozen-lockfile && bun run build
        chdir: /var/www/webapp

    - name: Run pending migrations
      ansible.builtin.command:
        cmd: php artisan migrate --force
        chdir: /var/www/webapp

    - name: Cache Laravel related stuff
      ansible.builtin.command:
        cmd: php artisan optimize
        chdir: /var/www/webapp

- name: Restart Video processing queue on video-preprocessor node
  hosts:
    - video-preprocessor-node
  any-errors-fatal: true
  tasks:
    - name: Restart Laravel queue for preprocessing videos
      ansible.builtin.command:
        cmd: php artisan queue:restart
        chdir: /var/www/webapp
