all:
  children:
    tnaflex_nodes:
      hosts:
        database-node:
          ansible_host: database-node
          private_ip: 192.168.122.101

        webapp-node:
          ansible_host: webapp-node
          private_ip: 192.168.122.102

        video-preprocessor-node:
          ansible_host: video-preprocessor-node
          private_ip: 192.168.122.103

      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/azureuser/.ssh/lab_ed25519
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
