name: Alert host of new changes so it deploys to webapp and video processing nodes.

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0

        with:
          ssh-private-key: ${{ secrets.HOST_SSH_KEY }}

      - name: Alert host of new changes by running the deploy ansible playbook
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -x
          
            vault_file="$(mktemp)"
            trap 'rm -f "$vault_file"' EXIT
            chmod 600 "$vault_file"
            printf '%s' "$VAULT_PASSWORD" > "$vault_file"

            cat $vault_file

            ansible-playbook -i ${{ secrets.HOST_PROJECT_DIR }}/ansible/inventory.yaml ${{ secrets.HOST_PROJECT_DIR }}/ansible/07-deploy-on-push.yaml --vault-id playground@$vault_file
            EOF